name = "VectorAutoRegressions"
uuid = "9faf6757-7d61-4c35-a2c5-e494469c5044"
authors = ["Logan Hotz"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
